### ISSUE TITLE
FX.php FileMaker Pro Server 12 Advanced

### ISSUE THREAD

**Issue by jpscharf** [yodarunamok/fxphp#18]
There is an issue with the `FMDBNames()` when used with FileMaker Server 12.

```
$DatasetQuery = new FX($serverIP, $webCompanionPort, $dataSourceType);
$DatabaseData = $DatasetQuery->FMDBNames();
```

In 11 it works fine, but in 12 it throws an error:
The xml URL `[[FM12 HOST]]:80/fmi/xml/FMPXMLRESULT.xml?-db=&-max=&-dbnames` will not work, but if I go the xml URL and remove `-db&-max&`, the url will now look like the following `[[FM12 HOST]]:80/fmi/xml/FMPXMLRESULT.xml?-dbnames` and will work.

**Comment by yodarunamok** [comment]
This appears to be working fine in version 6.10 of FX.php, and was apparently addressed back in 2013.
