### ISSUE TITLE
Deprecation of `/e` in `preg_replace()`

### ISSUE THREAD

**Issue by opensaurusrex** [yodarunamok/fxphp#25]
I wanted to point this out so that you would know that it was coming up:

    Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in .../fxphp/datasource_classes/RetrieveFMXML.class.php on line 217

**Comment by yodarunamok** [comment]
This has been addressed.  Also, fix is present in development branch.
