### ISSUE TITLE
There is no license

### ISSUE THREAD

**Issue by matatirosolutions** [yodarunamok/fxphp#38]
In order to use this codebase in some projects a license is required to ensure that we can prove to clients we have the right to use the code - just saying it's 'free and open source' isn't enough.

Please could you add a license - given the age, scope and intent of the project I would suggest MIT.

**Comment by TyrfingMjolnir** [comment]
There is the artistic license; if you read the license folder.

**Comment by matatirosolutions** [comment]
My bad - used to seeing the license in the Github header.
